--- #assignment
- hosts: machine
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes 


  tasks:
    - name: install httpd
      action: yum pkg=httpd state=present

    - name: start httpd
      action: service name=httpd state=started

    - name: copy index
      action: copy src=/mnt/22q1/practical/index.html dest=/var/www/html

